<a href="https://colab.research.google.com/github/param1707/Pandas/blob/main/CreatingDataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Different ways of creating dataframe**

# **Creating a dataframe from csv file**

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/pandas/3_different_ways_of_creating_dataframe/weather_data.csv')

In [3]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

# **Creating a dataframe from excel file**

In [4]:
df1 = pd.read_excel("weather_data.xlsx","Sheet1")

In [5]:
df1

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

# **Creating a dataframe from dictionary**

In [6]:
weather_data = {
    'day':['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature':[32,35,28,24,32,31],
    'windspeed':[6,7,2,7,4,2],
    'event':['Rain','Sunny','Snow','Snow','Rain','Sunny']
}

In [7]:
df2 = pd.DataFrame(weather_data)
df2

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

# **Creating a dataframe from list of tuples**

In [11]:
weather_data = [
        ('1/1/2017',32,6,'Rain') ,
        ('1/2/2017',35,7,'Sunny'),
        ('1/6/2017',31,2,'Sunny')       

]

In [13]:
df3 = pd.DataFrame(weather_data)
df3

          0   1  2      3
0  1/1/2017  32  6   Rain
1  1/2/2017  35  7  Sunny
2  1/6/2017  31  2  Sunny

# **changing the column of dataframe**

In [15]:
df3 = pd.DataFrame(weather_data,columns=['day','temperature','windspeed','event'])
df3

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/6/2017           31          2  Sunny

# **Creating dataframe from list of dictionaries**

In [16]:
weather_data = [
        {'day':'1/1/2017','temperature':32,'windspeed':6,'event':'Rain'} ,
        {'day':'1/2/2017','temperature':35,'windspeed':7,'event':'Sunny'},
        {'day':'1/6/2017','temperature':31,'windspeed':2,'event':'Sunny'}
]

In [17]:
df4 = pd.DataFrame(weather_data)
df4

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/6/2017           31          2  Sunny